### ISSUE TITLE
Deprecate and remove existing Sugar Labs Social Help features

### ISSUE THREAD

**Issue by quozl** [geekrypter/Sugar-Labs-Social#6]
A previous project added a Social Help feature to Sugar, and now you're proposing a Sugar Labs Social feature ... again. :grin:

In adding this new feature to Sugar Labs, please ensure you deprecate and remove the corresponding components from the previous project;

* [ ] the Social Help server, a Discourse instance hosted at sugarlabs.org,
* [ ] the Sugar desktop configuration setting, keyboard shortcut, and menu items.

Thanks!

**Comment by geekrypter** [comment]
Ok 👍
